### ISSUE TITLE
"Check" button never gets enabled

### ISSUE THREAD

**Issue by citronalco** [markdoliner/check_xmpp_dns#4]
At least in Firefox the "Check" button does not get enabled when entering a host name.

Javascript complains about "Uncaught TypeError: document.getElementById(...) is null" in
```
function validate(field) {
    document.getElementById('submit_button').disabled = (field.value.length == 0);
}
```
The button is defined as:
```
<input disabled="disabled" sid="submit_button" type="submit" value="Check">
```
After removing the "s" from "sid" everything works.

**Comment by markdoliner** [comment]
Thanks for letting me know about this! I just checked in a fix and updated the code on kingant.net. It looks like I had fixed that locally on kingant.net years ago but never checked in the change. Then I lost the change when I moved to a new server a few weeks ago and cloned from the repo rather than copying from the old server. Thanks again!
